const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
class E {constructor(tag='div'){this.tag=tag;this.children=[];this.textContent='';this.value='0';this.open=false;this.disabled=false;this.style={setProperty(){}};this.handlers={};this.attrs={};}replaceChildren(...c){this.children=c;}append(...c){this.children.push(...c);}setAttribute(k,v){this.attrs[k]=v;}addEventListener(k,f){this.handlers[k]=f;}focus(){this.focused=true;}}
const ids=['operations-history','history-window','history-status','history-metrics','history-chart','history-samples','history-record','history-detail','history-refresh'];const nodes=Object.fromEntries(ids.map(x=>[x,new E()]));let next={status:'SYNTHETIC_CASE',points:[]};const events={};let requests=0;
const context={document:{getElementById:id=>nodes[id],createElement:t=>new E(t),createElementNS:(ns,t)=>new E(t)},window:{addEventListener:(k,f)=>events[k]=f},fetch:async()=>{requests++;return next===null?{ok:false}:{ok:true,json:async()=>next}},Date,Number,JSON,console};
vm.runInNewContext(fs.readFileSync('/private/tmp/m20-finalization-cold-20260909-release85d6/workspace/operations-history.js','utf8'),context);
const flush=()=>new Promise(r=>setImmediate(r)); const refresh=async()=>{await nodes['history-refresh'].handlers.click();await flush();};
const point=(id,q)=>({id,observed_at:new Date(Date.now()+q*1000).toISOString(),case_id:'FIXTURE',source_id:'local',uom:'Box',currency:'USD',metrics:{received:q,recorded:q},documents:[]});
(async()=>{await flush();assert.equal(nodes['history-metrics'].children.length,0);assert.match(nodes['history-chart'].children[0].textContent,/Open a connected case/);assert.equal(nodes['history-refresh'].disabled,false);
next={status:'AVAILABLE',points:[point('1',1)]};await refresh();assert.equal(nodes['history-metrics'].children.length,6);assert.equal(nodes['history-samples'].children.length,1);nodes['history-samples'].children[0].handlers.click();assert.equal(nodes['history-detail'].open,true);
next={status:'AVAILABLE',points:[point('1',1),point('2',2)]};await refresh();assert.equal(nodes['history-chart'].children[0].tag,'svg');nodes['history-metrics'].children[0].handlers.keydown({key:'ArrowRight',preventDefault(){}});assert.equal(nodes['history-metrics'].children[1].attrs['aria-checked'],'true');
next={status:'SYNTHETIC_CASE',points:[]};await refresh();assert.equal(nodes['history-metrics'].children.length,0);assert.equal(nodes['history-samples'].children.length,0);assert.equal(nodes['history-record'].children.length,0);assert.equal(nodes['history-detail'].open,false);
next=null;await refresh();assert.match(nodes['history-status'].textContent,/could not be read/);assert.equal(nodes['history-refresh'].disabled,false);assert.equal(nodes['history-metrics'].children.length,6);
next={status:'AVAILABLE',points:[point('3',3)]};await refresh();assert.equal(nodes['history-metrics'].children.length,6);assert.equal(nodes['history-samples'].children.length,1);
next={status:'SYNTHETIC_CASE',points:[point('4',4)]};await refresh();assert.equal(nodes['history-metrics'].children.length,6);
next={status:'AVAILABLE',points:[{...point('old',1),observed_at:'2000-01-01T00:00:00Z'}]};nodes['history-window'].value='24';nodes['history-window'].handlers.change();await flush();assert.equal(nodes['history-metrics'].children.length,6);assert.match(nodes['history-status'].textContent,/No observations in this window/);
console.log(JSON.stringify({passed:true,requests,cases:['synthetic-empty','real-one','real-multiple','radio-keyboard','real-to-synthetic-clears-details','source-unavailable','retry-real','synthetic-with-points-preserved','empty-real-time-window']},null,2));})().catch(e=>{console.error(e);process.exitCode=1;});
