"""Dependency-light lifecycle vocabulary and the only allowed transition table."""

from __future__ import annotations

from enum import StrEnum


class CaseStatus(StrEnum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
    PROTECTED = "PROTECTED"
    RECEIPT_ALREADY_VERIFIED = "RECEIPT_ALREADY_VERIFIED"
    RECEIPT_RESTART_RECOMMENDED = "RECEIPT_RESTART_RECOMMENDED"
    AWAITING_RECEIPT_APPROVAL = "AWAITING_RECEIPT_APPROVAL"
    RECEIPT_ACTION_AUTHORIZED = "RECEIPT_ACTION_AUTHORIZED"
    RECEIPT_EXECUTING = "RECEIPT_EXECUTING"
    RECEIPT_VERIFIED = "RECEIPT_VERIFIED"
    AWAITING_INVOICE_APPROVAL = "AWAITING_INVOICE_APPROVAL"
    INVOICE_ACTION_AUTHORIZED = "INVOICE_ACTION_AUTHORIZED"
    INVOICE_EXECUTING = "INVOICE_EXECUTING"
    CLOSED = "CLOSED"


class TransitionEvent(StrEnum):
    INVESTIGATION_STARTED = "INVESTIGATION_STARTED"
    EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"
    EVIDENCE_ADMITTED = "EVIDENCE_ADMITTED"
    ACTION_PROTECTED = "ACTION_PROTECTED"
    RECEIPT_ALREADY_POSTED = "RECEIPT_ALREADY_POSTED"
    RECEIPT_RESTART_RECOMMENDED = "RECEIPT_RESTART_RECOMMENDED"
    RECEIPT_APPROVAL_REQUESTED = "RECEIPT_APPROVAL_REQUESTED"
    RECEIPT_APPROVAL_ACCEPTED = "RECEIPT_APPROVAL_ACCEPTED"
    RECEIPT_EXECUTION_STARTED = "RECEIPT_EXECUTION_STARTED"
    RECEIPT_POSTCONDITIONS_VERIFIED = "RECEIPT_POSTCONDITIONS_VERIFIED"
    INVOICE_APPROVAL_REQUESTED = "INVOICE_APPROVAL_REQUESTED"
    INVOICE_APPROVAL_ACCEPTED = "INVOICE_APPROVAL_ACCEPTED"
    INVOICE_EXECUTION_STARTED = "INVOICE_EXECUTION_STARTED"
    INVOICE_POSTCONDITIONS_VERIFIED = "INVOICE_POSTCONDITIONS_VERIFIED"


TRANSITIONS: dict[tuple[CaseStatus, TransitionEvent], CaseStatus] = {
    (CaseStatus.OPEN, TransitionEvent.INVESTIGATION_STARTED): CaseStatus.INVESTIGATING,
    (CaseStatus.INVESTIGATING, TransitionEvent.EVIDENCE_REQUIRED): CaseStatus.NEEDS_EVIDENCE,
    (CaseStatus.NEEDS_EVIDENCE, TransitionEvent.EVIDENCE_ADMITTED): CaseStatus.INVESTIGATING,
    (CaseStatus.INVESTIGATING, TransitionEvent.ACTION_PROTECTED): CaseStatus.PROTECTED,
    (
        CaseStatus.INVESTIGATING,
        TransitionEvent.RECEIPT_ALREADY_POSTED,
    ): CaseStatus.RECEIPT_ALREADY_VERIFIED,
    (
        CaseStatus.RECEIPT_ALREADY_VERIFIED,
        TransitionEvent.INVOICE_APPROVAL_REQUESTED,
    ): CaseStatus.AWAITING_INVOICE_APPROVAL,
    (
        CaseStatus.INVESTIGATING,
        TransitionEvent.RECEIPT_RESTART_RECOMMENDED,
    ): CaseStatus.RECEIPT_RESTART_RECOMMENDED,
    (
        CaseStatus.RECEIPT_RESTART_RECOMMENDED,
        TransitionEvent.RECEIPT_APPROVAL_REQUESTED,
    ): CaseStatus.AWAITING_RECEIPT_APPROVAL,
    (
        CaseStatus.AWAITING_RECEIPT_APPROVAL,
        TransitionEvent.RECEIPT_APPROVAL_ACCEPTED,
    ): CaseStatus.RECEIPT_ACTION_AUTHORIZED,
    (
        CaseStatus.RECEIPT_ACTION_AUTHORIZED,
        TransitionEvent.RECEIPT_EXECUTION_STARTED,
    ): CaseStatus.RECEIPT_EXECUTING,
    (
        CaseStatus.RECEIPT_EXECUTING,
        TransitionEvent.RECEIPT_POSTCONDITIONS_VERIFIED,
    ): CaseStatus.RECEIPT_VERIFIED,
    (
        CaseStatus.RECEIPT_VERIFIED,
        TransitionEvent.INVOICE_APPROVAL_REQUESTED,
    ): CaseStatus.AWAITING_INVOICE_APPROVAL,
    (
        CaseStatus.AWAITING_INVOICE_APPROVAL,
        TransitionEvent.INVOICE_APPROVAL_ACCEPTED,
    ): CaseStatus.INVOICE_ACTION_AUTHORIZED,
    (
        CaseStatus.INVOICE_ACTION_AUTHORIZED,
        TransitionEvent.INVOICE_EXECUTION_STARTED,
    ): CaseStatus.INVOICE_EXECUTING,
    (
        CaseStatus.INVOICE_EXECUTING,
        TransitionEvent.INVOICE_POSTCONDITIONS_VERIFIED,
    ): CaseStatus.CLOSED,
}


TERMINAL_STATUSES = frozenset({CaseStatus.PROTECTED, CaseStatus.CLOSED})
