"""Authority Rebaseline B contracts and bounded orchestration.

The package is deliberately separate from the historical ``agents`` contracts.  The
advisory branch can contain model-produced investigation material, while the
``classifier`` and ``quorum`` modules form the deterministic operational boundary.
"""

from the_missing_20.authority_b.advisory import (
    ADVISORY_READ_ONLY_TOOLS,
    AdvisoryOrchestrator,
    advisory_from_harness_run,
    normalize_advisory_failure,
    validate_advisory_tool_names,
)
from the_missing_20.authority_b.classifier import (
    DeterministicDecisionLedger,
    classify_operational_state,
    evaluate_operational_policy,
)
from the_missing_20.authority_b.executor import AuthorityBControlledExecutor
from the_missing_20.authority_b.frozen_evidence import (
    AUTHORITY_B_FROZEN_EVIDENCE_DIGESTS,
    AUTHORITY_B_FROZEN_EVIDENCE_VERSION,
    frozen_evidence_digest,
    frozen_evidence_matches,
)
from the_missing_20.authority_b.models import (
    ADVISORY_AUTHORITY_LABEL,
    AdvisoryDissent,
    AdvisoryHypothesis,
    AdvisoryInvestigation,
    AdvisoryKnowledgeCitation,
    AdvisoryStatus,
    AdvisoryUsage,
    AIUsefulnessProof,
    AttestationDecision,
    AuthorizationIntent,
    DecisionWorkspaceSnapshot,
    EvidenceClass,
    EvidenceDisposition,
    M4AcceptanceStatus,
    M4PromotionStatus,
    OperationalClassification,
    OperationalDecision,
    OperationalEligibility,
    ProofCheck,
    ProofStatus,
    QuorumActionGrant,
    QuorumAttestation,
    QuorumResult,
    QuorumStatus,
    SafetyProof,
    transition_advisory_status,
)
from the_missing_20.authority_b.proofs import (
    build_ai_usefulness_proof,
    build_safety_proof,
)
from the_missing_20.authority_b.provider import (
    AUTHORITY_B_CLAIM_PATH,
    AUTHORITY_B_CUMULATIVE_COST_CAP_USD,
    AUTHORITY_B_FAILURE_PATH,
    AUTHORITY_B_INCREMENTAL_COST_CAP_USD,
    AUTHORITY_B_INPUT_TOKEN_CAP,
    AUTHORITY_B_MAX_OUTPUT_TOKENS_PER_REQUEST,
    AUTHORITY_B_OUTPUT_TOKEN_CAP,
    AUTHORITY_B_PRIOR_ESTIMATED_COST_USD,
    AUTHORITY_B_REQUEST_CAP,
    AUTHORITY_B_SUCCESS_PATH,
    AuthorityBAttemptAlreadyClaimed,
    AuthorityBAttemptClaim,
    AuthorityBOutcome,
    claim_authority_b_attempt,
    load_authority_b_attempt_claim,
)
from the_missing_20.authority_b.quorum import (
    AuthorityBExecutor,
    PrincipalDirectory,
    QuorumAuthorizationService,
    QuorumDenied,
)
from the_missing_20.authority_b.records import AuthorityBArtifactStore, AuthorityBRecordConflict
from the_missing_20.authority_b.workflow import AuthorityBRun, run_authority_b
from the_missing_20.authority_b.workspace import build_workspace_snapshot

__all__ = [
    "ADVISORY_AUTHORITY_LABEL",
    "ADVISORY_READ_ONLY_TOOLS",
    "AUTHORITY_B_CLAIM_PATH",
    "AUTHORITY_B_CUMULATIVE_COST_CAP_USD",
    "AUTHORITY_B_FAILURE_PATH",
    "AUTHORITY_B_INCREMENTAL_COST_CAP_USD",
    "AUTHORITY_B_INPUT_TOKEN_CAP",
    "AUTHORITY_B_MAX_OUTPUT_TOKENS_PER_REQUEST",
    "AUTHORITY_B_OUTPUT_TOKEN_CAP",
    "AUTHORITY_B_PRIOR_ESTIMATED_COST_USD",
    "AUTHORITY_B_REQUEST_CAP",
    "AUTHORITY_B_SUCCESS_PATH",
    "AdvisoryDissent",
    "AdvisoryHypothesis",
    "AdvisoryInvestigation",
    "AdvisoryKnowledgeCitation",
    "AdvisoryOrchestrator",
    "AdvisoryStatus",
    "AdvisoryUsage",
    "AIUsefulnessProof",
    "AttestationDecision",
    "AuthorizationIntent",
    "AuthorityBAttemptAlreadyClaimed",
    "AuthorityBAttemptClaim",
    "AuthorityBArtifactStore",
    "AuthorityBExecutor",
    "AuthorityBControlledExecutor",
    "AUTHORITY_B_FROZEN_EVIDENCE_DIGESTS",
    "AUTHORITY_B_FROZEN_EVIDENCE_VERSION",
    "AuthorityBOutcome",
    "AuthorityBRecordConflict",
    "AuthorityBRun",
    "DecisionWorkspaceSnapshot",
    "EvidenceClass",
    "EvidenceDisposition",
    "M4AcceptanceStatus",
    "M4PromotionStatus",
    "DeterministicDecisionLedger",
    "OperationalClassification",
    "OperationalDecision",
    "OperationalEligibility",
    "PrincipalDirectory",
    "ProofCheck",
    "ProofStatus",
    "QuorumActionGrant",
    "QuorumAttestation",
    "QuorumAuthorizationService",
    "QuorumDenied",
    "QuorumResult",
    "QuorumStatus",
    "SafetyProof",
    "advisory_from_harness_run",
    "build_ai_usefulness_proof",
    "build_safety_proof",
    "build_workspace_snapshot",
    "claim_authority_b_attempt",
    "classify_operational_state",
    "evaluate_operational_policy",
    "load_authority_b_attempt_claim",
    "normalize_advisory_failure",
    "frozen_evidence_digest",
    "frozen_evidence_matches",
    "run_authority_b",
    "validate_advisory_tool_names",
    "transition_advisory_status",
]
